const state = {
  active:       false,
  autoRepeat:   true,
  queue:        [],
  playNext:     [],
  pos:          0,
  els:          [],
  meta:         [],
  worker:       null,
  busy:         false,
  loading:      false,
  lastTitle:    '',
  lastProgress: 0,
  sidebarOpen:  false,
  manualAction: false,
  dragSrc:      null,
  history:      [],
  priority:     {},    // ti → weight: 0.25 low, 1.0 normal, 2.0 high
  suspended:    false,
  playlistUrl:  '',
  _savedStats:  null,
  stats: {
    played:     0,
    playCounts: {},
    elapsed:    0,
  },
};
